Updated run commands
qase-tms/qasectl pull request #8
Opened 2024-05-09 15:20 UTC by gibiw

Fix the API v1 client
--
- removed project code from the client constructor
- changed the auth header name

---

Add a run service
--
- added a client interface
- added create and complete methods

---

Updated run commands
--
- updated the `create` test run command
- added the `complete` test run command
- changed the command structure in the `cmd` folder
- added support CLI and ENV parameters 
- disabled `auth`, `import`, `set` commands

2024-05-09 16:03 UTC, NickVolynkin commented on cmd/auth.go
> +//}
does it stay commented?

2024-05-09 16:04 UTC, gibiw commented on cmd/auth.go
> +//}
I will remove or change it in new versions. I have disabled old commands

2024-05-10 04:19 UTC, NickVolynkin commented on cmd/root.go
> +	Short: "This is a CLI tool for Qase TestOps",
```suggestion
	Short: "CLI tool for Qase TestOps",
```

2024-05-10 04:21 UTC, NickVolynkin commented on cmd/run/create/create.go
> +		Example: "qasectl run create --title 'My test run' --description 'This is a test run' --project 'PRJ' --token 'TOKEN'",
Again `qasectl`, not `qli`?

2024-05-10 04:22 UTC, NickVolynkin commented on go.mod
> +	github.com/spf13/viper v1.18.2
what's the point of having two `require (... )` blocks?

2024-05-10 04:28 UTC, NickVolynkin commented on cmd/version/version.go
> +func VersionCmd() *cobra.Command {
Tried the version command:
```console
$ ./build/qli version
Error: required flag(s) "project", "token" not set
Usage:
  qasectl version [flags]

...

$ ./build/qli version -p a -t b
Qase CLI vv0.1.4-4-g46313a0

2024-05-10 04:45 UTC, NickVolynkin commented on cmd/run/complete/complete.go
> +	cmd := &cobra.Command{
Successful command gives no feedback, just blank line. Should be something like
```
Run ${id} completed
```

Using with a run ID that doesn't exist, I get error 404:

```
 ./build/qli run complete -t asdf -p DEMO --id 44                                                
Error: 404 Not Found
Usage:
  qasectl run complete [flags]
  
Examples:
qasectl run complete --id 123 --project 'PRJ' --token 'TOKEN'
...
```

2024-05-10 04:50 UTC, NickVolynkin commented on cmd/run/create/create.go
> +	cmd := &cobra.Command{
Tests

* no token or project: error message about token and project
* no title: `run create` help message
* with token, project and title — ok
* with token, project, title, and description - ok
* same but `--title ''`: Error 400 Bad Request. Not very informative.
* same but `--project ''`: Error: code must have at least 2 elements. I'd say 'characters', but okay.

2024-05-10 04:51 UTC, NickVolynkin commented on cmd/run/create/create.go
> +	cmd := &cobra.Command{
Overall: nothing blocking, let's roll as it is and improve later.

2024-05-10 04:54 UTC, NickVolynkin requested changes
The only blocking problem is that `qli help`, `qli version` and `qli completion` show an error message about token and project being required. All the rest is okay, we can roll as it is now and improve later.

2024-05-10 07:46 UTC, gibiw commented on go.mod
> +	github.com/spf13/viper v1.18.2
yes.
In the first block, Go stores direct dependencies. 
The second block stores the dependencies on which the direct dependencies depend.

2024-05-10 08:36 UTC, gibiw commented on cmd/root.go
> +	Short: "This is a CLI tool for Qase TestOps",
fixed

2024-05-10 08:36 UTC, gibiw commented on cmd/run/create/create.go
> +		Example: "qasectl run create --title 'My test run' --description 'This is a test run' --project 'PRJ' --token 'TOKEN'",
fixed

2024-05-10 08:36 UTC, gibiw commented on cmd/version/version.go
> +func VersionCmd() *cobra.Command {
fixed

2024-05-10 08:38 UTC, gibiw commented on cmd/run/complete/complete.go
> +	cmd := &cobra.Command{
Added a message about the successful completion of the run test and if the run test was not found

2024-05-10 08:39 UTC, gibiw commented on cmd/run/create/create.go
> +	cmd := &cobra.Command{
I will think about parameter validation in future versions.

2024-05-10 10:31 UTC, merged